######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 20 18:44:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
OBJECTS_DIR = .obj
CONFIG -= app_bundle
